Exercício 1 - Calcular Quantidade de Vogais
gurgelff/orion-bootcamp pull request #1
Opened 2023-10-10 01:04 UTC by gurgelff

Utilizei uma página HTML estática para mostrar o uso da função através de parâmetro - _item a)_ - e também para demonstrar a funcionalidade a partir do formulário - _item b)_ - de modo visual, surtindo efeitos nessa página.

Eu inclui os arquivos de configuração relativos ao NodeJS e PNPM (gerenciador de pacotes _diferenciado_). Por enquanto, apenas o Typescript está sendo utilizado como pacote.

O cerne da funcionalidade reside no uso da função filter() numa lista de caracteres (após aplicar split na string) para retornar apenas as vogais, com suporte a vogais com acentos. Daí, basta retornar o tamanho desse array de vogais.

Maiores instruções no **README**.

2023-10-11 02:35 UTC, carlosrizon requested changes

2023-10-11 02:35 UTC, carlosrizon commented on package.json
> +    "typescript": "^5.2.2"
Uma boa pratica e fixar as versões

2023-10-11 02:35 UTC, carlosrizon commented on pnpm-lock.yaml
> +lockfileVersion: '6.0'
Arquivos lock não devem subir ao repo.

2023-10-12 18:32 UTC, gurgelff commented on package.json
> +    "typescript": "^5.2.2"
Feito

2023-10-12 18:33 UTC, gurgelff commented on pnpm-lock.yaml
> +lockfileVersion: '6.0'
Executei git rm --cached
Feito

2023-10-13 16:29 UTC, gurgelff commented
Alterações aprovadas de acordo com o Trello

2023-10-13 16:30 UTC, merged